# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import verification_pb2 as verification__pb2


class VerificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckClient = channel.unary_unary(
                '/verif.Verification/CheckClient',
                request_serializer=verification__pb2.PhonePinRequest.SerializeToString,
                response_deserializer=verification__pb2.StatusResponse.FromString,
                )


class VerificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckClient,
                    request_deserializer=verification__pb2.PhonePinRequest.FromString,
                    response_serializer=verification__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verif.Verification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Verification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verif.Verification/CheckClient',
            verification__pb2.PhonePinRequest.SerializeToString,
            verification__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
