// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: verification.proto

#ifndef PROTOBUF_INCLUDED_verification_2eproto
#define PROTOBUF_INCLUDED_verification_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_verification_2eproto 

namespace protobuf_verification_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_verification_2eproto
namespace verif {
class PhonePinRequest;
class PhonePinRequestDefaultTypeInternal;
extern PhonePinRequestDefaultTypeInternal _PhonePinRequest_default_instance_;
class StatusResponse;
class StatusResponseDefaultTypeInternal;
extern StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;
}  // namespace verif
namespace google {
namespace protobuf {
template<> ::verif::PhonePinRequest* Arena::CreateMaybeMessage<::verif::PhonePinRequest>(Arena*);
template<> ::verif::StatusResponse* Arena::CreateMaybeMessage<::verif::StatusResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace verif {

// ===================================================================

class PhonePinRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:verif.PhonePinRequest) */ {
 public:
  PhonePinRequest();
  virtual ~PhonePinRequest();

  PhonePinRequest(const PhonePinRequest& from);

  inline PhonePinRequest& operator=(const PhonePinRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PhonePinRequest(PhonePinRequest&& from) noexcept
    : PhonePinRequest() {
    *this = ::std::move(from);
  }

  inline PhonePinRequest& operator=(PhonePinRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PhonePinRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PhonePinRequest* internal_default_instance() {
    return reinterpret_cast<const PhonePinRequest*>(
               &_PhonePinRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PhonePinRequest* other);
  friend void swap(PhonePinRequest& a, PhonePinRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PhonePinRequest* New() const final {
    return CreateMaybeMessage<PhonePinRequest>(NULL);
  }

  PhonePinRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PhonePinRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PhonePinRequest& from);
  void MergeFrom(const PhonePinRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PhonePinRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 phone = 1;
  void clear_phone();
  static const int kPhoneFieldNumber = 1;
  ::google::protobuf::int64 phone() const;
  void set_phone(::google::protobuf::int64 value);

  // int64 pin = 2;
  void clear_pin();
  static const int kPinFieldNumber = 2;
  ::google::protobuf::int64 pin() const;
  void set_pin(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:verif.PhonePinRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 phone_;
  ::google::protobuf::int64 pin_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_verification_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StatusResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:verif.StatusResponse) */ {
 public:
  StatusResponse();
  virtual ~StatusResponse();

  StatusResponse(const StatusResponse& from);

  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusResponse(StatusResponse&& from) noexcept
    : StatusResponse() {
    *this = ::std::move(from);
  }

  inline StatusResponse& operator=(StatusResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusResponse* internal_default_instance() {
    return reinterpret_cast<const StatusResponse*>(
               &_StatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(StatusResponse* other);
  friend void swap(StatusResponse& a, StatusResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusResponse* New() const final {
    return CreateMaybeMessage<StatusResponse>(NULL);
  }

  StatusResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatusResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatusResponse& from);
  void MergeFrom(const StatusResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  bool status() const;
  void set_status(bool value);

  // @@protoc_insertion_point(class_scope:verif.StatusResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool status_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_verification_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PhonePinRequest

// int64 phone = 1;
inline void PhonePinRequest::clear_phone() {
  phone_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PhonePinRequest::phone() const {
  // @@protoc_insertion_point(field_get:verif.PhonePinRequest.phone)
  return phone_;
}
inline void PhonePinRequest::set_phone(::google::protobuf::int64 value) {
  
  phone_ = value;
  // @@protoc_insertion_point(field_set:verif.PhonePinRequest.phone)
}

// int64 pin = 2;
inline void PhonePinRequest::clear_pin() {
  pin_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PhonePinRequest::pin() const {
  // @@protoc_insertion_point(field_get:verif.PhonePinRequest.pin)
  return pin_;
}
inline void PhonePinRequest::set_pin(::google::protobuf::int64 value) {
  
  pin_ = value;
  // @@protoc_insertion_point(field_set:verif.PhonePinRequest.pin)
}

// -------------------------------------------------------------------

// StatusResponse

// bool status = 1;
inline void StatusResponse::clear_status() {
  status_ = false;
}
inline bool StatusResponse::status() const {
  // @@protoc_insertion_point(field_get:verif.StatusResponse.status)
  return status_;
}
inline void StatusResponse::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:verif.StatusResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace verif

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_verification_2eproto
