# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verification.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("verification.proto", :syntax => :proto3) do
    add_message "PhonePinRequest" do
      optional :phone, :int64, 1
      optional :pin, :int64, 2
    end
    add_message "StatusResponse" do
      optional :status, :bool, 1
    end
  end
end

PhonePinRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PhonePinRequest").msgclass
StatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StatusResponse").msgclass
